#!/usr/bin/env bash
#  Script bash that displays the time for 12 hours and 59 minutes
hour=0
minute=1
while [ $h -le 12 ]; do
	echo "Hour: ${h}"
	while [ $m -lt 60 ]; do
		echo $m
		(( m+=1))
	done
	(( m=1 ))
	(( h+=1 ))
done
